dist: build
builds:
  - binary: mongodb_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
    flags:
      - -v
    ldflags:
        - -s -w -X main.version=v{{.Version}} -X main.commit={{.ShortCommit}} -X main.buildDate={{.Date}}
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
snapshot:
  name_template: "{{ .ShortCommit }}"
changelog:
  skip: true
release:
  github:
    owner: percona
    name: mongodb_exporter
  draft: true
  prerelease: auto
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - "percona/mongodb_exporter:{{.Major}}.{{.Minor}}"
  - "percona/mongodb_exporter:{{.Version}}"
  dockerfile: Dockerfile
  use: buildx
nfpms:
  - file_name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    homepage:  https://www.percona.com/
    description: MongoDB exporter for Prometheus
    maintainer: Percona
    vendor: Percona
    license: Apache 2.0
    formats:
    - deb
    - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64-bit
    scripts:
      postinstall: ".scripts/postinst"
    contents:
      - src: .scripts/systemd/mongodb_exporter.service
        dst: /etc/systemd/system/mongodb_exporter.service
        type: "config|noreplace"
      - src: .scripts/default/mongodb_exporter.example
        dst: /etc/default/mongodb_exporter.example
